services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    container_name: ${SERVICE_NAME}-dev
    stdin_open: true
    tty: true
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - SERVICE_NAME=${SERVICE_NAME}

  jaeger:
    image: jaegertracing/all-in-one:1.31
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
